[package]
name = "database_course"
version = "0.1.0"
authors = ["antongHU <1514974209@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.1"
chrono = "0.4"